Document: biosig4c++
Title: Debian biosig4c++ Manual
Author: <insert document author here>
Abstract: This manual describes what biosig4c++ is
 and how it can be used to
 manage online manuals on Debian systems.
Section: unknown

Format: debiandoc-sgml
Files: /usr/share/doc/biosig4c++/biosig4c++.sgml.gz

Format: postscript
Files: /usr/share/doc/biosig4c++/biosig4c++.ps.gz

Format: text
Files: /usr/share/doc/biosig4c++/biosig4c++.text.gz

Format: HTML
Index: /usr/share/doc/biosig4c++/html/index.html
Files: /usr/share/doc/biosig4c++/html/*.html
